[package]
name = "test_rust_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
indicatif = "0.17.5"
crossbeam-channel = "0.5.8"
ipnetwork = "0.20.0"